# Generated by Django 4.0.1 on 2022-02-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directortecnico',
            name='aniosExperiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='copasGanadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='goles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='persona',
            name='copasGanadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fechaDePublicacion',
            field=models.DateField(auto_now=True),
        ),
    ]
