# Generated by Django 4.0.1 on 2022-02-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_directortecnico_aniosexperiencia_equipo_copasganadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fechaDePublicacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
