# Generated by Django 4.0.1 on 2022-02-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
