# Generated by Django 4.0.1 on 2022-01-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_tecnico', models.CharField(max_length=40)),
                ('anio_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=30)),
                ('anio_nacimiento', models.DateField()),
                ('copas_ganadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_jugador', models.CharField(max_length=40)),
                ('posicion_jugador', models.CharField(max_length=30)),
                ('cantidad_goles', models.IntegerField()),
                ('anio_nacimiento', models.DateField()),
            ],
        ),
    ]
