# Generated by Django 4.0.1 on 2022-01-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='nombre_equipo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='jugadores',
            old_name='apellido_jugador',
            new_name='apellido',
        ),
        migrations.RemoveField(
            model_name='directortecnico',
            name='anio_nacimiento',
        ),
        migrations.RemoveField(
            model_name='directortecnico',
            name='apellido_tecnico',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='anio_nacimiento',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='anio_nacimiento',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='posicion_jugador',
        ),
        migrations.AddField(
            model_name='directortecnico',
            name='apellido',
            field=models.CharField(default='apellido', max_length=40),
            preserve_default=False,
        ),
    ]
